blank_issues_enabled: true
contact_links:
  - name: Pastas Discussions
    url: https://github.com/orgs/pastas/discussions
    about: Please open a discussion if you have questions, thoughts or ideas.
