name: CI SPELLING

on:
  pull_request:
    branches:
      - master

jobs:
  code-spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          check-latest: true
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Setup tox environment
        run: tox -e codespell --notest

      - name: Test
        run: tox -e codespell --skip-pkg-install