name: CI SPELLING

on:
  pull_request:
    branches:
      - master

jobs:
  code-spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
          enable-cache: true

      - name: Install dependencies
        run: uv pip install tox-uv

      - name: Setup tox environment
        run: uv run tox -e codespell --notest

      - name: Test
        run: uv run tox -e codespell --skip-pkg-install