name: CI RUFF

on:
  push:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Formatting and linting with ruff
            python: "3.11"
            toxenv: ruff
          - name: Formatting and linting with ruff (Preview Mode)
            python: "3.11"
            toxenv: ruff_preview
    env:
      # Color Output
      # Rich (pip)
      FORCE_COLOR: 1
      # Tox
      PY_COLORS: 1
      # Pytest
      PYTEST_ADDOPTS: "--color=yes"
    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python }}
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv
          uv pip install tox-uv

      - name: Setup tox environment
        run: uv run tox -e ${{ matrix.toxenv }} --notest

      - name: Test
        run: uv run tox -e ${{ matrix.toxenv }} --skip-pkg-install

