name: Code Spell Check on Release

on:
  pull_request:
    branches:
      - master

jobs:
  code-spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell[toml]

      - name: Run codespell
        run: codespell